// Code generated by ent, DO NOT EDIT.

package email

import (
	"saas_identidad/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Email {
	return predicate.Email(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Email {
	return predicate.Email(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Email {
	return predicate.Email(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Email {
	return predicate.Email(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Email {
	return predicate.Email(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Email {
	return predicate.Email(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Email {
	return predicate.Email(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Email {
	return predicate.Email(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Email {
	return predicate.Email(sql.FieldLTE(FieldID, id))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.Email {
	return predicate.Email(sql.FieldEQ(FieldEmail, v))
}

// PaswordHash applies equality check predicate on the "pasword_hash" field. It's identical to PaswordHashEQ.
func PaswordHash(v string) predicate.Email {
	return predicate.Email(sql.FieldEQ(FieldPaswordHash, v))
}

// CreateAt applies equality check predicate on the "create_at" field. It's identical to CreateAtEQ.
func CreateAt(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldEQ(FieldCreateAt, v))
}

// UpdateAt applies equality check predicate on the "update_at" field. It's identical to UpdateAtEQ.
func UpdateAt(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldEQ(FieldUpdateAt, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.Email {
	return predicate.Email(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.Email {
	return predicate.Email(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.Email {
	return predicate.Email(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.Email {
	return predicate.Email(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.Email {
	return predicate.Email(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.Email {
	return predicate.Email(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.Email {
	return predicate.Email(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.Email {
	return predicate.Email(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.Email {
	return predicate.Email(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.Email {
	return predicate.Email(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.Email {
	return predicate.Email(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.Email {
	return predicate.Email(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.Email {
	return predicate.Email(sql.FieldContainsFold(FieldEmail, v))
}

// PaswordHashEQ applies the EQ predicate on the "pasword_hash" field.
func PaswordHashEQ(v string) predicate.Email {
	return predicate.Email(sql.FieldEQ(FieldPaswordHash, v))
}

// PaswordHashNEQ applies the NEQ predicate on the "pasword_hash" field.
func PaswordHashNEQ(v string) predicate.Email {
	return predicate.Email(sql.FieldNEQ(FieldPaswordHash, v))
}

// PaswordHashIn applies the In predicate on the "pasword_hash" field.
func PaswordHashIn(vs ...string) predicate.Email {
	return predicate.Email(sql.FieldIn(FieldPaswordHash, vs...))
}

// PaswordHashNotIn applies the NotIn predicate on the "pasword_hash" field.
func PaswordHashNotIn(vs ...string) predicate.Email {
	return predicate.Email(sql.FieldNotIn(FieldPaswordHash, vs...))
}

// PaswordHashGT applies the GT predicate on the "pasword_hash" field.
func PaswordHashGT(v string) predicate.Email {
	return predicate.Email(sql.FieldGT(FieldPaswordHash, v))
}

// PaswordHashGTE applies the GTE predicate on the "pasword_hash" field.
func PaswordHashGTE(v string) predicate.Email {
	return predicate.Email(sql.FieldGTE(FieldPaswordHash, v))
}

// PaswordHashLT applies the LT predicate on the "pasword_hash" field.
func PaswordHashLT(v string) predicate.Email {
	return predicate.Email(sql.FieldLT(FieldPaswordHash, v))
}

// PaswordHashLTE applies the LTE predicate on the "pasword_hash" field.
func PaswordHashLTE(v string) predicate.Email {
	return predicate.Email(sql.FieldLTE(FieldPaswordHash, v))
}

// PaswordHashContains applies the Contains predicate on the "pasword_hash" field.
func PaswordHashContains(v string) predicate.Email {
	return predicate.Email(sql.FieldContains(FieldPaswordHash, v))
}

// PaswordHashHasPrefix applies the HasPrefix predicate on the "pasword_hash" field.
func PaswordHashHasPrefix(v string) predicate.Email {
	return predicate.Email(sql.FieldHasPrefix(FieldPaswordHash, v))
}

// PaswordHashHasSuffix applies the HasSuffix predicate on the "pasword_hash" field.
func PaswordHashHasSuffix(v string) predicate.Email {
	return predicate.Email(sql.FieldHasSuffix(FieldPaswordHash, v))
}

// PaswordHashEqualFold applies the EqualFold predicate on the "pasword_hash" field.
func PaswordHashEqualFold(v string) predicate.Email {
	return predicate.Email(sql.FieldEqualFold(FieldPaswordHash, v))
}

// PaswordHashContainsFold applies the ContainsFold predicate on the "pasword_hash" field.
func PaswordHashContainsFold(v string) predicate.Email {
	return predicate.Email(sql.FieldContainsFold(FieldPaswordHash, v))
}

// AccountEQ applies the EQ predicate on the "account" field.
func AccountEQ(v Account) predicate.Email {
	return predicate.Email(sql.FieldEQ(FieldAccount, v))
}

// AccountNEQ applies the NEQ predicate on the "account" field.
func AccountNEQ(v Account) predicate.Email {
	return predicate.Email(sql.FieldNEQ(FieldAccount, v))
}

// AccountIn applies the In predicate on the "account" field.
func AccountIn(vs ...Account) predicate.Email {
	return predicate.Email(sql.FieldIn(FieldAccount, vs...))
}

// AccountNotIn applies the NotIn predicate on the "account" field.
func AccountNotIn(vs ...Account) predicate.Email {
	return predicate.Email(sql.FieldNotIn(FieldAccount, vs...))
}

// CreateAtEQ applies the EQ predicate on the "create_at" field.
func CreateAtEQ(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldEQ(FieldCreateAt, v))
}

// CreateAtNEQ applies the NEQ predicate on the "create_at" field.
func CreateAtNEQ(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldNEQ(FieldCreateAt, v))
}

// CreateAtIn applies the In predicate on the "create_at" field.
func CreateAtIn(vs ...time.Time) predicate.Email {
	return predicate.Email(sql.FieldIn(FieldCreateAt, vs...))
}

// CreateAtNotIn applies the NotIn predicate on the "create_at" field.
func CreateAtNotIn(vs ...time.Time) predicate.Email {
	return predicate.Email(sql.FieldNotIn(FieldCreateAt, vs...))
}

// CreateAtGT applies the GT predicate on the "create_at" field.
func CreateAtGT(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldGT(FieldCreateAt, v))
}

// CreateAtGTE applies the GTE predicate on the "create_at" field.
func CreateAtGTE(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldGTE(FieldCreateAt, v))
}

// CreateAtLT applies the LT predicate on the "create_at" field.
func CreateAtLT(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldLT(FieldCreateAt, v))
}

// CreateAtLTE applies the LTE predicate on the "create_at" field.
func CreateAtLTE(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldLTE(FieldCreateAt, v))
}

// UpdateAtEQ applies the EQ predicate on the "update_at" field.
func UpdateAtEQ(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldEQ(FieldUpdateAt, v))
}

// UpdateAtNEQ applies the NEQ predicate on the "update_at" field.
func UpdateAtNEQ(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldNEQ(FieldUpdateAt, v))
}

// UpdateAtIn applies the In predicate on the "update_at" field.
func UpdateAtIn(vs ...time.Time) predicate.Email {
	return predicate.Email(sql.FieldIn(FieldUpdateAt, vs...))
}

// UpdateAtNotIn applies the NotIn predicate on the "update_at" field.
func UpdateAtNotIn(vs ...time.Time) predicate.Email {
	return predicate.Email(sql.FieldNotIn(FieldUpdateAt, vs...))
}

// UpdateAtGT applies the GT predicate on the "update_at" field.
func UpdateAtGT(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldGT(FieldUpdateAt, v))
}

// UpdateAtGTE applies the GTE predicate on the "update_at" field.
func UpdateAtGTE(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldGTE(FieldUpdateAt, v))
}

// UpdateAtLT applies the LT predicate on the "update_at" field.
func UpdateAtLT(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldLT(FieldUpdateAt, v))
}

// UpdateAtLTE applies the LTE predicate on the "update_at" field.
func UpdateAtLTE(v time.Time) predicate.Email {
	return predicate.Email(sql.FieldLTE(FieldUpdateAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Email {
	return predicate.Email(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Email {
	return predicate.Email(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEmployees applies the HasEdge predicate on the "employees" edge.
func HasEmployees() predicate.Email {
	return predicate.Email(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EmployeesTable, EmployeesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEmployeesWith applies the HasEdge predicate on the "employees" edge with a given conditions (other predicates).
func HasEmployeesWith(preds ...predicate.Employee) predicate.Email {
	return predicate.Email(func(s *sql.Selector) {
		step := newEmployeesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Email) predicate.Email {
	return predicate.Email(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Email) predicate.Email {
	return predicate.Email(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Email) predicate.Email {
	return predicate.Email(sql.NotPredicates(p))
}
