// Code generated by ent, DO NOT EDIT.

package invitationemployee

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the invitationemployee type in the database.
	Label = "invitation_employee"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDepartment holds the string denoting the department field in the database.
	FieldDepartment = "department"
	// FieldPosition holds the string denoting the position field in the database.
	FieldPosition = "position"
	// EdgeInvitation holds the string denoting the invitation edge name in mutations.
	EdgeInvitation = "invitation"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// EdgeBranch holds the string denoting the branch edge name in mutations.
	EdgeBranch = "branch"
	// Table holds the table name of the invitationemployee in the database.
	Table = "invitation_employees"
	// InvitationTable is the table that holds the invitation relation/edge.
	InvitationTable = "invitation_employees"
	// InvitationInverseTable is the table name for the Invitation entity.
	// It exists in this package in order to avoid circular dependency with the "invitation" package.
	InvitationInverseTable = "invitations"
	// InvitationColumn is the table column denoting the invitation relation/edge.
	InvitationColumn = "invitation_invitation_employee"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "invitation_employees"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenants"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_invitation_employees"
	// BranchTable is the table that holds the branch relation/edge.
	BranchTable = "invitation_employees"
	// BranchInverseTable is the table name for the Branch entity.
	// It exists in this package in order to avoid circular dependency with the "branch" package.
	BranchInverseTable = "branches"
	// BranchColumn is the table column denoting the branch relation/edge.
	BranchColumn = "branch_invitation_employees"
)

// Columns holds all SQL columns for invitationemployee fields.
var Columns = []string{
	FieldID,
	FieldDepartment,
	FieldPosition,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "invitation_employees"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"branch_invitation_employees",
	"invitation_invitation_employee",
	"tenant_invitation_employees",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DepartmentValidator is a validator for the "department" field. It is called by the builders before save.
	DepartmentValidator func(string) error
	// PositionValidator is a validator for the "position" field. It is called by the builders before save.
	PositionValidator func(string) error
)

// OrderOption defines the ordering options for the InvitationEmployee queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDepartment orders the results by the department field.
func ByDepartment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDepartment, opts...).ToFunc()
}

// ByPosition orders the results by the position field.
func ByPosition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPosition, opts...).ToFunc()
}

// ByInvitationField orders the results by invitation field.
func ByInvitationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInvitationStep(), sql.OrderByField(field, opts...))
	}
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}

// ByBranchField orders the results by branch field.
func ByBranchField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBranchStep(), sql.OrderByField(field, opts...))
	}
}
func newInvitationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InvitationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, InvitationTable, InvitationColumn),
	)
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
	)
}
func newBranchStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BranchInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, BranchTable, BranchColumn),
	)
}
