// Code generated by ent, DO NOT EDIT.

package invitationemployee

import (
	"saas_identidad/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldLTE(FieldID, id))
}

// Department applies equality check predicate on the "department" field. It's identical to DepartmentEQ.
func Department(v string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldEQ(FieldDepartment, v))
}

// Position applies equality check predicate on the "position" field. It's identical to PositionEQ.
func Position(v string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldEQ(FieldPosition, v))
}

// DepartmentEQ applies the EQ predicate on the "department" field.
func DepartmentEQ(v string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldEQ(FieldDepartment, v))
}

// DepartmentNEQ applies the NEQ predicate on the "department" field.
func DepartmentNEQ(v string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldNEQ(FieldDepartment, v))
}

// DepartmentIn applies the In predicate on the "department" field.
func DepartmentIn(vs ...string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldIn(FieldDepartment, vs...))
}

// DepartmentNotIn applies the NotIn predicate on the "department" field.
func DepartmentNotIn(vs ...string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldNotIn(FieldDepartment, vs...))
}

// DepartmentGT applies the GT predicate on the "department" field.
func DepartmentGT(v string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldGT(FieldDepartment, v))
}

// DepartmentGTE applies the GTE predicate on the "department" field.
func DepartmentGTE(v string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldGTE(FieldDepartment, v))
}

// DepartmentLT applies the LT predicate on the "department" field.
func DepartmentLT(v string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldLT(FieldDepartment, v))
}

// DepartmentLTE applies the LTE predicate on the "department" field.
func DepartmentLTE(v string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldLTE(FieldDepartment, v))
}

// DepartmentContains applies the Contains predicate on the "department" field.
func DepartmentContains(v string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldContains(FieldDepartment, v))
}

// DepartmentHasPrefix applies the HasPrefix predicate on the "department" field.
func DepartmentHasPrefix(v string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldHasPrefix(FieldDepartment, v))
}

// DepartmentHasSuffix applies the HasSuffix predicate on the "department" field.
func DepartmentHasSuffix(v string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldHasSuffix(FieldDepartment, v))
}

// DepartmentEqualFold applies the EqualFold predicate on the "department" field.
func DepartmentEqualFold(v string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldEqualFold(FieldDepartment, v))
}

// DepartmentContainsFold applies the ContainsFold predicate on the "department" field.
func DepartmentContainsFold(v string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldContainsFold(FieldDepartment, v))
}

// PositionEQ applies the EQ predicate on the "position" field.
func PositionEQ(v string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldEQ(FieldPosition, v))
}

// PositionNEQ applies the NEQ predicate on the "position" field.
func PositionNEQ(v string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldNEQ(FieldPosition, v))
}

// PositionIn applies the In predicate on the "position" field.
func PositionIn(vs ...string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldIn(FieldPosition, vs...))
}

// PositionNotIn applies the NotIn predicate on the "position" field.
func PositionNotIn(vs ...string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldNotIn(FieldPosition, vs...))
}

// PositionGT applies the GT predicate on the "position" field.
func PositionGT(v string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldGT(FieldPosition, v))
}

// PositionGTE applies the GTE predicate on the "position" field.
func PositionGTE(v string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldGTE(FieldPosition, v))
}

// PositionLT applies the LT predicate on the "position" field.
func PositionLT(v string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldLT(FieldPosition, v))
}

// PositionLTE applies the LTE predicate on the "position" field.
func PositionLTE(v string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldLTE(FieldPosition, v))
}

// PositionContains applies the Contains predicate on the "position" field.
func PositionContains(v string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldContains(FieldPosition, v))
}

// PositionHasPrefix applies the HasPrefix predicate on the "position" field.
func PositionHasPrefix(v string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldHasPrefix(FieldPosition, v))
}

// PositionHasSuffix applies the HasSuffix predicate on the "position" field.
func PositionHasSuffix(v string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldHasSuffix(FieldPosition, v))
}

// PositionEqualFold applies the EqualFold predicate on the "position" field.
func PositionEqualFold(v string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldEqualFold(FieldPosition, v))
}

// PositionContainsFold applies the ContainsFold predicate on the "position" field.
func PositionContainsFold(v string) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.FieldContainsFold(FieldPosition, v))
}

// HasInvitation applies the HasEdge predicate on the "invitation" edge.
func HasInvitation() predicate.InvitationEmployee {
	return predicate.InvitationEmployee(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, InvitationTable, InvitationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInvitationWith applies the HasEdge predicate on the "invitation" edge with a given conditions (other predicates).
func HasInvitationWith(preds ...predicate.Invitation) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(func(s *sql.Selector) {
		step := newInvitationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.InvitationEmployee {
	return predicate.InvitationEmployee(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBranch applies the HasEdge predicate on the "branch" edge.
func HasBranch() predicate.InvitationEmployee {
	return predicate.InvitationEmployee(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BranchTable, BranchColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBranchWith applies the HasEdge predicate on the "branch" edge with a given conditions (other predicates).
func HasBranchWith(preds ...predicate.Branch) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(func(s *sql.Selector) {
		step := newBranchStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.InvitationEmployee) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.InvitationEmployee) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.InvitationEmployee) predicate.InvitationEmployee {
	return predicate.InvitationEmployee(sql.NotPredicates(p))
}
