// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"saas_identidad/ent/branch"
	"saas_identidad/ent/employee"
	"saas_identidad/ent/plan"
	"saas_identidad/ent/schemas"
	"saas_identidad/ent/tenant"
	"saas_identidad/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	branchFields := schemas.Branch{}.Fields()
	_ = branchFields
	// branchDescName is the schema descriptor for name field.
	branchDescName := branchFields[0].Descriptor()
	// branch.NameValidator is a validator for the "name" field. It is called by the builders before save.
	branch.NameValidator = func() func(string) error {
		validators := branchDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// branchDescPhone is the schema descriptor for phone field.
	branchDescPhone := branchFields[1].Descriptor()
	// branch.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	branch.PhoneValidator = branchDescPhone.Validators[0].(func(string) error)
	// branchDescStreet is the schema descriptor for street field.
	branchDescStreet := branchFields[2].Descriptor()
	// branch.StreetValidator is a validator for the "street" field. It is called by the builders before save.
	branch.StreetValidator = func() func(string) error {
		validators := branchDescStreet.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(street string) error {
			for _, fn := range fns {
				if err := fn(street); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// branchDescZone is the schema descriptor for zone field.
	branchDescZone := branchFields[3].Descriptor()
	// branch.ZoneValidator is a validator for the "zone" field. It is called by the builders before save.
	branch.ZoneValidator = branchDescZone.Validators[0].(func(string) error)
	// branchDescReference is the schema descriptor for reference field.
	branchDescReference := branchFields[4].Descriptor()
	// branch.ReferenceValidator is a validator for the "reference" field. It is called by the builders before save.
	branch.ReferenceValidator = branchDescReference.Validators[0].(func(string) error)
	// branchDescCity is the schema descriptor for city field.
	branchDescCity := branchFields[5].Descriptor()
	// branch.DefaultCity holds the default value on creation for the city field.
	branch.DefaultCity = branchDescCity.Default.(string)
	// branch.CityValidator is a validator for the "city" field. It is called by the builders before save.
	branch.CityValidator = func() func(string) error {
		validators := branchDescCity.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(city string) error {
			for _, fn := range fns {
				if err := fn(city); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// branchDescIsActive is the schema descriptor for is_active field.
	branchDescIsActive := branchFields[7].Descriptor()
	// branch.DefaultIsActive holds the default value on creation for the is_active field.
	branch.DefaultIsActive = branchDescIsActive.Default.(bool)
	// branchDescCreateAt is the schema descriptor for create_at field.
	branchDescCreateAt := branchFields[8].Descriptor()
	// branch.DefaultCreateAt holds the default value on creation for the create_at field.
	branch.DefaultCreateAt = branchDescCreateAt.Default.(func() time.Time)
	employeeHooks := schemas.Employee{}.Hooks()
	employee.Hooks[0] = employeeHooks[0]
	employeeFields := schemas.Employee{}.Fields()
	_ = employeeFields
	// employeeDescPosition is the schema descriptor for position field.
	employeeDescPosition := employeeFields[1].Descriptor()
	// employee.PositionValidator is a validator for the "position" field. It is called by the builders before save.
	employee.PositionValidator = employeeDescPosition.Validators[0].(func(string) error)
	// employeeDescActive is the schema descriptor for active field.
	employeeDescActive := employeeFields[2].Descriptor()
	// employee.DefaultActive holds the default value on creation for the active field.
	employee.DefaultActive = employeeDescActive.Default.(bool)
	// employeeDescJoinAt is the schema descriptor for join_at field.
	employeeDescJoinAt := employeeFields[3].Descriptor()
	// employee.DefaultJoinAt holds the default value on creation for the join_at field.
	employee.DefaultJoinAt = employeeDescJoinAt.Default.(func() time.Time)
	planFields := schemas.Plan{}.Fields()
	_ = planFields
	// planDescSubscription is the schema descriptor for subscription field.
	planDescSubscription := planFields[0].Descriptor()
	// plan.SubscriptionValidator is a validator for the "subscription" field. It is called by the builders before save.
	plan.SubscriptionValidator = planDescSubscription.Validators[0].(func(string) error)
	// planDescPrice is the schema descriptor for price field.
	planDescPrice := planFields[1].Descriptor()
	// plan.DefaultPrice holds the default value on creation for the price field.
	plan.DefaultPrice = planDescPrice.Default.(float64)
	// planDescMaxUsers is the schema descriptor for max_users field.
	planDescMaxUsers := planFields[2].Descriptor()
	// plan.DefaultMaxUsers holds the default value on creation for the max_users field.
	plan.DefaultMaxUsers = planDescMaxUsers.Default.(int32)
	// planDescMaxBranch is the schema descriptor for max_branch field.
	planDescMaxBranch := planFields[3].Descriptor()
	// plan.DefaultMaxBranch holds the default value on creation for the max_branch field.
	plan.DefaultMaxBranch = planDescMaxBranch.Default.(int32)
	// planDescMaxBoss is the schema descriptor for max_boss field.
	planDescMaxBoss := planFields[4].Descriptor()
	// plan.DefaultMaxBoss holds the default value on creation for the max_boss field.
	plan.DefaultMaxBoss = planDescMaxBoss.Default.(int32)
	tenantFields := schemas.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[0].Descriptor()
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = func() func(string) error {
		validators := tenantDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	userFields := schemas.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = func() func(string) error {
		validators := userDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescLastName is the schema descriptor for last_name field.
	userDescLastName := userFields[1].Descriptor()
	// user.LastNameValidator is a validator for the "last_name" field. It is called by the builders before save.
	user.LastNameValidator = func() func(string) error {
		validators := userDescLastName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(last_name string) error {
			for _, fn := range fns {
				if err := fn(last_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescCi is the schema descriptor for ci field.
	userDescCi := userFields[2].Descriptor()
	// user.CiValidator is a validator for the "ci" field. It is called by the builders before save.
	user.CiValidator = userDescCi.Validators[0].(func(int) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[4].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[5].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
}

const (
	Version = "v0.14.6"                                         // Version of ent codegen.
	Sum     = "h1:/f2696BpwuWAEEG6PVGWflg6+Inrpq4pRWuNlWz/Skk=" // Sum of ent codegen.
)
