// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BranchesColumns holds the columns for the "branches" table.
	BranchesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "phone", Type: field.TypeString, Nullable: true, Size: 14},
		{Name: "street", Type: field.TypeString, Size: 150},
		{Name: "zone", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "reference", Type: field.TypeString, Nullable: true, Size: 200},
		{Name: "city", Type: field.TypeString, Size: 50, Default: "Santa Cruz de la Sierra"},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"LP", "SC", "CB", "OR", "PT", "TJ", "CH", "BE", "PA"}, Default: "SC"},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "create_at", Type: field.TypeTime},
		{Name: "tenant_branchs", Type: field.TypeInt, Nullable: true},
	}
	// BranchesTable holds the schema information for the "branches" table.
	BranchesTable = &schema.Table{
		Name:       "branches",
		Columns:    BranchesColumns,
		PrimaryKey: []*schema.Column{BranchesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "branches_tenants_branchs",
				Columns:    []*schema.Column{BranchesColumns[10]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// EmployeesColumns holds the columns for the "employees" table.
	EmployeesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "area", Type: field.TypeEnum, Enums: []string{"office", "logistics", "plant", "commercial"}},
		{Name: "position", Type: field.TypeString, Size: 30},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "join_at", Type: field.TypeTime},
		{Name: "left_at", Type: field.TypeTime, Nullable: true},
		{Name: "branch_employees", Type: field.TypeInt, Nullable: true},
		{Name: "tenant_employees", Type: field.TypeInt, Nullable: true},
		{Name: "user_employees", Type: field.TypeInt, Nullable: true},
	}
	// EmployeesTable holds the schema information for the "employees" table.
	EmployeesTable = &schema.Table{
		Name:       "employees",
		Columns:    EmployeesColumns,
		PrimaryKey: []*schema.Column{EmployeesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "employees_branches_employees",
				Columns:    []*schema.Column{EmployeesColumns[6]},
				RefColumns: []*schema.Column{BranchesColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "employees_tenants_employees",
				Columns:    []*schema.Column{EmployeesColumns[7]},
				RefColumns: []*schema.Column{TenantsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "employees_users_employees",
				Columns:    []*schema.Column{EmployeesColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// PlansColumns holds the columns for the "plans" table.
	PlansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "subscription", Type: field.TypeString, Size: 20},
		{Name: "price", Type: field.TypeFloat64, Default: 0, SchemaType: map[string]string{"postgres": "decimal(7,2)"}},
		{Name: "max_users", Type: field.TypeInt32, Default: 5},
		{Name: "max_branch", Type: field.TypeInt32, Default: 2},
		{Name: "max_boss", Type: field.TypeInt32, Default: 1},
	}
	// PlansTable holds the schema information for the "plans" table.
	PlansTable = &schema.Table{
		Name:       "plans",
		Columns:    PlansColumns,
		PrimaryKey: []*schema.Column{PlansColumns[0]},
	}
	// TenantsColumns holds the columns for the "tenants" table.
	TenantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 50},
		{Name: "end_suscription", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "plan_tenants", Type: field.TypeInt, Nullable: true},
	}
	// TenantsTable holds the schema information for the "tenants" table.
	TenantsTable = &schema.Table{
		Name:       "tenants",
		Columns:    TenantsColumns,
		PrimaryKey: []*schema.Column{TenantsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tenants_plans_tenants",
				Columns:    []*schema.Column{TenantsColumns[3]},
				RefColumns: []*schema.Column{PlansColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 50},
		{Name: "last_name", Type: field.TypeString, Size: 50},
		{Name: "ci", Type: field.TypeInt},
		{Name: "date_birth", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "password_hash", Type: field.TypeString, Size: 150},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BranchesTable,
		EmployeesTable,
		PlansTable,
		TenantsTable,
		UsersTable,
	}
)

func init() {
	BranchesTable.ForeignKeys[0].RefTable = TenantsTable
	EmployeesTable.ForeignKeys[0].RefTable = BranchesTable
	EmployeesTable.ForeignKeys[1].RefTable = TenantsTable
	EmployeesTable.ForeignKeys[2].RefTable = UsersTable
	TenantsTable.ForeignKeys[0].RefTable = PlansTable
}
