// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"saas_identidad/ent/branch"
	"saas_identidad/ent/employee"
	"saas_identidad/ent/tenant"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BranchCreate is the builder for creating a Branch entity.
type BranchCreate struct {
	config
	mutation *BranchMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *BranchCreate) SetName(v string) *BranchCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPhone sets the "phone" field.
func (_c *BranchCreate) SetPhone(v string) *BranchCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_c *BranchCreate) SetNillablePhone(v *string) *BranchCreate {
	if v != nil {
		_c.SetPhone(*v)
	}
	return _c
}

// SetStreet sets the "street" field.
func (_c *BranchCreate) SetStreet(v string) *BranchCreate {
	_c.mutation.SetStreet(v)
	return _c
}

// SetZone sets the "zone" field.
func (_c *BranchCreate) SetZone(v string) *BranchCreate {
	_c.mutation.SetZone(v)
	return _c
}

// SetNillableZone sets the "zone" field if the given value is not nil.
func (_c *BranchCreate) SetNillableZone(v *string) *BranchCreate {
	if v != nil {
		_c.SetZone(*v)
	}
	return _c
}

// SetReference sets the "reference" field.
func (_c *BranchCreate) SetReference(v string) *BranchCreate {
	_c.mutation.SetReference(v)
	return _c
}

// SetNillableReference sets the "reference" field if the given value is not nil.
func (_c *BranchCreate) SetNillableReference(v *string) *BranchCreate {
	if v != nil {
		_c.SetReference(*v)
	}
	return _c
}

// SetCity sets the "city" field.
func (_c *BranchCreate) SetCity(v string) *BranchCreate {
	_c.mutation.SetCity(v)
	return _c
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_c *BranchCreate) SetNillableCity(v *string) *BranchCreate {
	if v != nil {
		_c.SetCity(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *BranchCreate) SetState(v branch.State) *BranchCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *BranchCreate) SetNillableState(v *branch.State) *BranchCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *BranchCreate) SetIsActive(v bool) *BranchCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *BranchCreate) SetNillableIsActive(v *bool) *BranchCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetCreateAt sets the "create_at" field.
func (_c *BranchCreate) SetCreateAt(v time.Time) *BranchCreate {
	_c.mutation.SetCreateAt(v)
	return _c
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (_c *BranchCreate) SetNillableCreateAt(v *time.Time) *BranchCreate {
	if v != nil {
		_c.SetCreateAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (_c *BranchCreate) SetTenantID(id int) *BranchCreate {
	_c.mutation.SetTenantID(id)
	return _c
}

// SetNillableTenantID sets the "tenant" edge to the Tenant entity by ID if the given value is not nil.
func (_c *BranchCreate) SetNillableTenantID(id *int) *BranchCreate {
	if id != nil {
		_c = _c.SetTenantID(*id)
	}
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *BranchCreate) SetTenant(v *Tenant) *BranchCreate {
	return _c.SetTenantID(v.ID)
}

// AddEmployeeIDs adds the "employees" edge to the Employee entity by IDs.
func (_c *BranchCreate) AddEmployeeIDs(ids ...int) *BranchCreate {
	_c.mutation.AddEmployeeIDs(ids...)
	return _c
}

// AddEmployees adds the "employees" edges to the Employee entity.
func (_c *BranchCreate) AddEmployees(v ...*Employee) *BranchCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEmployeeIDs(ids...)
}

// Mutation returns the BranchMutation object of the builder.
func (_c *BranchCreate) Mutation() *BranchMutation {
	return _c.mutation
}

// Save creates the Branch in the database.
func (_c *BranchCreate) Save(ctx context.Context) (*Branch, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BranchCreate) SaveX(ctx context.Context) *Branch {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BranchCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BranchCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BranchCreate) defaults() {
	if _, ok := _c.mutation.City(); !ok {
		v := branch.DefaultCity
		_c.mutation.SetCity(v)
	}
	if _, ok := _c.mutation.State(); !ok {
		v := branch.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := branch.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreateAt(); !ok {
		v := branch.DefaultCreateAt()
		_c.mutation.SetCreateAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BranchCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Branch.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := branch.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Branch.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Phone(); ok {
		if err := branch.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "Branch.phone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Street(); !ok {
		return &ValidationError{Name: "street", err: errors.New(`ent: missing required field "Branch.street"`)}
	}
	if v, ok := _c.mutation.Street(); ok {
		if err := branch.StreetValidator(v); err != nil {
			return &ValidationError{Name: "street", err: fmt.Errorf(`ent: validator failed for field "Branch.street": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Zone(); ok {
		if err := branch.ZoneValidator(v); err != nil {
			return &ValidationError{Name: "zone", err: fmt.Errorf(`ent: validator failed for field "Branch.zone": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Reference(); ok {
		if err := branch.ReferenceValidator(v); err != nil {
			return &ValidationError{Name: "reference", err: fmt.Errorf(`ent: validator failed for field "Branch.reference": %w`, err)}
		}
	}
	if _, ok := _c.mutation.City(); !ok {
		return &ValidationError{Name: "city", err: errors.New(`ent: missing required field "Branch.city"`)}
	}
	if v, ok := _c.mutation.City(); ok {
		if err := branch.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Branch.city": %w`, err)}
		}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "Branch.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := branch.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Branch.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Branch.is_active"`)}
	}
	if _, ok := _c.mutation.CreateAt(); !ok {
		return &ValidationError{Name: "create_at", err: errors.New(`ent: missing required field "Branch.create_at"`)}
	}
	return nil
}

func (_c *BranchCreate) sqlSave(ctx context.Context) (*Branch, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BranchCreate) createSpec() (*Branch, *sqlgraph.CreateSpec) {
	var (
		_node = &Branch{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(branch.Table, sqlgraph.NewFieldSpec(branch.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(branch.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(branch.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := _c.mutation.Street(); ok {
		_spec.SetField(branch.FieldStreet, field.TypeString, value)
		_node.Street = value
	}
	if value, ok := _c.mutation.Zone(); ok {
		_spec.SetField(branch.FieldZone, field.TypeString, value)
		_node.Zone = value
	}
	if value, ok := _c.mutation.Reference(); ok {
		_spec.SetField(branch.FieldReference, field.TypeString, value)
		_node.Reference = value
	}
	if value, ok := _c.mutation.City(); ok {
		_spec.SetField(branch.FieldCity, field.TypeString, value)
		_node.City = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(branch.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(branch.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.CreateAt(); ok {
		_spec.SetField(branch.FieldCreateAt, field.TypeTime, value)
		_node.CreateAt = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   branch.TenantTable,
			Columns: []string{branch.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.tenant_branchs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EmployeesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   branch.EmployeesTable,
			Columns: []string{branch.EmployeesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BranchCreateBulk is the builder for creating many Branch entities in bulk.
type BranchCreateBulk struct {
	config
	err      error
	builders []*BranchCreate
}

// Save creates the Branch entities in the database.
func (_c *BranchCreateBulk) Save(ctx context.Context) ([]*Branch, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Branch, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BranchMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BranchCreateBulk) SaveX(ctx context.Context) []*Branch {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BranchCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BranchCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
