// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"saas_identidad/ent/branch"
	"saas_identidad/ent/invitation"
	"saas_identidad/ent/invitationemployee"
	"saas_identidad/ent/predicate"
	"saas_identidad/ent/tenant"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InvitationEmployeeQuery is the builder for querying InvitationEmployee entities.
type InvitationEmployeeQuery struct {
	config
	ctx            *QueryContext
	order          []invitationemployee.OrderOption
	inters         []Interceptor
	predicates     []predicate.InvitationEmployee
	withInvitation *InvitationQuery
	withTenant     *TenantQuery
	withBranch     *BranchQuery
	withFKs        bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the InvitationEmployeeQuery builder.
func (_q *InvitationEmployeeQuery) Where(ps ...predicate.InvitationEmployee) *InvitationEmployeeQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *InvitationEmployeeQuery) Limit(limit int) *InvitationEmployeeQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *InvitationEmployeeQuery) Offset(offset int) *InvitationEmployeeQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *InvitationEmployeeQuery) Unique(unique bool) *InvitationEmployeeQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *InvitationEmployeeQuery) Order(o ...invitationemployee.OrderOption) *InvitationEmployeeQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryInvitation chains the current query on the "invitation" edge.
func (_q *InvitationEmployeeQuery) QueryInvitation() *InvitationQuery {
	query := (&InvitationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(invitationemployee.Table, invitationemployee.FieldID, selector),
			sqlgraph.To(invitation.Table, invitation.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, invitationemployee.InvitationTable, invitationemployee.InvitationColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTenant chains the current query on the "tenant" edge.
func (_q *InvitationEmployeeQuery) QueryTenant() *TenantQuery {
	query := (&TenantClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(invitationemployee.Table, invitationemployee.FieldID, selector),
			sqlgraph.To(tenant.Table, tenant.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, invitationemployee.TenantTable, invitationemployee.TenantColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBranch chains the current query on the "branch" edge.
func (_q *InvitationEmployeeQuery) QueryBranch() *BranchQuery {
	query := (&BranchClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(invitationemployee.Table, invitationemployee.FieldID, selector),
			sqlgraph.To(branch.Table, branch.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, invitationemployee.BranchTable, invitationemployee.BranchColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first InvitationEmployee entity from the query.
// Returns a *NotFoundError when no InvitationEmployee was found.
func (_q *InvitationEmployeeQuery) First(ctx context.Context) (*InvitationEmployee, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{invitationemployee.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *InvitationEmployeeQuery) FirstX(ctx context.Context) *InvitationEmployee {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first InvitationEmployee ID from the query.
// Returns a *NotFoundError when no InvitationEmployee ID was found.
func (_q *InvitationEmployeeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{invitationemployee.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *InvitationEmployeeQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single InvitationEmployee entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one InvitationEmployee entity is found.
// Returns a *NotFoundError when no InvitationEmployee entities are found.
func (_q *InvitationEmployeeQuery) Only(ctx context.Context) (*InvitationEmployee, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{invitationemployee.Label}
	default:
		return nil, &NotSingularError{invitationemployee.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *InvitationEmployeeQuery) OnlyX(ctx context.Context) *InvitationEmployee {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only InvitationEmployee ID in the query.
// Returns a *NotSingularError when more than one InvitationEmployee ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *InvitationEmployeeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{invitationemployee.Label}
	default:
		err = &NotSingularError{invitationemployee.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *InvitationEmployeeQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of InvitationEmployees.
func (_q *InvitationEmployeeQuery) All(ctx context.Context) ([]*InvitationEmployee, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*InvitationEmployee, *InvitationEmployeeQuery]()
	return withInterceptors[[]*InvitationEmployee](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *InvitationEmployeeQuery) AllX(ctx context.Context) []*InvitationEmployee {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of InvitationEmployee IDs.
func (_q *InvitationEmployeeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(invitationemployee.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *InvitationEmployeeQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *InvitationEmployeeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*InvitationEmployeeQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *InvitationEmployeeQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *InvitationEmployeeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *InvitationEmployeeQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the InvitationEmployeeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *InvitationEmployeeQuery) Clone() *InvitationEmployeeQuery {
	if _q == nil {
		return nil
	}
	return &InvitationEmployeeQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]invitationemployee.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.InvitationEmployee{}, _q.predicates...),
		withInvitation: _q.withInvitation.Clone(),
		withTenant:     _q.withTenant.Clone(),
		withBranch:     _q.withBranch.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithInvitation tells the query-builder to eager-load the nodes that are connected to
// the "invitation" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *InvitationEmployeeQuery) WithInvitation(opts ...func(*InvitationQuery)) *InvitationEmployeeQuery {
	query := (&InvitationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withInvitation = query
	return _q
}

// WithTenant tells the query-builder to eager-load the nodes that are connected to
// the "tenant" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *InvitationEmployeeQuery) WithTenant(opts ...func(*TenantQuery)) *InvitationEmployeeQuery {
	query := (&TenantClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTenant = query
	return _q
}

// WithBranch tells the query-builder to eager-load the nodes that are connected to
// the "branch" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *InvitationEmployeeQuery) WithBranch(opts ...func(*BranchQuery)) *InvitationEmployeeQuery {
	query := (&BranchClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBranch = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Department string `json:"department,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.InvitationEmployee.Query().
//		GroupBy(invitationemployee.FieldDepartment).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *InvitationEmployeeQuery) GroupBy(field string, fields ...string) *InvitationEmployeeGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &InvitationEmployeeGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = invitationemployee.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Department string `json:"department,omitempty"`
//	}
//
//	client.InvitationEmployee.Query().
//		Select(invitationemployee.FieldDepartment).
//		Scan(ctx, &v)
func (_q *InvitationEmployeeQuery) Select(fields ...string) *InvitationEmployeeSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &InvitationEmployeeSelect{InvitationEmployeeQuery: _q}
	sbuild.label = invitationemployee.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a InvitationEmployeeSelect configured with the given aggregations.
func (_q *InvitationEmployeeQuery) Aggregate(fns ...AggregateFunc) *InvitationEmployeeSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *InvitationEmployeeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !invitationemployee.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *InvitationEmployeeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*InvitationEmployee, error) {
	var (
		nodes       = []*InvitationEmployee{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withInvitation != nil,
			_q.withTenant != nil,
			_q.withBranch != nil,
		}
	)
	if _q.withInvitation != nil || _q.withTenant != nil || _q.withBranch != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, invitationemployee.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*InvitationEmployee).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &InvitationEmployee{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withInvitation; query != nil {
		if err := _q.loadInvitation(ctx, query, nodes, nil,
			func(n *InvitationEmployee, e *Invitation) { n.Edges.Invitation = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTenant; query != nil {
		if err := _q.loadTenant(ctx, query, nodes, nil,
			func(n *InvitationEmployee, e *Tenant) { n.Edges.Tenant = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withBranch; query != nil {
		if err := _q.loadBranch(ctx, query, nodes, nil,
			func(n *InvitationEmployee, e *Branch) { n.Edges.Branch = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *InvitationEmployeeQuery) loadInvitation(ctx context.Context, query *InvitationQuery, nodes []*InvitationEmployee, init func(*InvitationEmployee), assign func(*InvitationEmployee, *Invitation)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*InvitationEmployee)
	for i := range nodes {
		if nodes[i].invitation_invitation_employee == nil {
			continue
		}
		fk := *nodes[i].invitation_invitation_employee
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(invitation.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "invitation_invitation_employee" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *InvitationEmployeeQuery) loadTenant(ctx context.Context, query *TenantQuery, nodes []*InvitationEmployee, init func(*InvitationEmployee), assign func(*InvitationEmployee, *Tenant)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*InvitationEmployee)
	for i := range nodes {
		if nodes[i].tenant_invitation_employees == nil {
			continue
		}
		fk := *nodes[i].tenant_invitation_employees
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tenant.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "tenant_invitation_employees" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *InvitationEmployeeQuery) loadBranch(ctx context.Context, query *BranchQuery, nodes []*InvitationEmployee, init func(*InvitationEmployee), assign func(*InvitationEmployee, *Branch)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*InvitationEmployee)
	for i := range nodes {
		if nodes[i].branch_invitation_employees == nil {
			continue
		}
		fk := *nodes[i].branch_invitation_employees
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(branch.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "branch_invitation_employees" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *InvitationEmployeeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *InvitationEmployeeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(invitationemployee.Table, invitationemployee.Columns, sqlgraph.NewFieldSpec(invitationemployee.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invitationemployee.FieldID)
		for i := range fields {
			if fields[i] != invitationemployee.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *InvitationEmployeeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(invitationemployee.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = invitationemployee.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// InvitationEmployeeGroupBy is the group-by builder for InvitationEmployee entities.
type InvitationEmployeeGroupBy struct {
	selector
	build *InvitationEmployeeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *InvitationEmployeeGroupBy) Aggregate(fns ...AggregateFunc) *InvitationEmployeeGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *InvitationEmployeeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InvitationEmployeeQuery, *InvitationEmployeeGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *InvitationEmployeeGroupBy) sqlScan(ctx context.Context, root *InvitationEmployeeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// InvitationEmployeeSelect is the builder for selecting fields of InvitationEmployee entities.
type InvitationEmployeeSelect struct {
	*InvitationEmployeeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *InvitationEmployeeSelect) Aggregate(fns ...AggregateFunc) *InvitationEmployeeSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *InvitationEmployeeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InvitationEmployeeQuery, *InvitationEmployeeSelect](ctx, _s.InvitationEmployeeQuery, _s, _s.inters, v)
}

func (_s *InvitationEmployeeSelect) sqlScan(ctx context.Context, root *InvitationEmployeeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
