// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"saas_identidad/ent/branch"
	"saas_identidad/ent/invitation"
	"saas_identidad/ent/invitationemployee"
	"saas_identidad/ent/tenant"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// InvitationEmployee is the model entity for the InvitationEmployee schema.
type InvitationEmployee struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Department holds the value of the "department" field.
	Department string `json:"department,omitempty"`
	// Position holds the value of the "position" field.
	Position string `json:"position,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InvitationEmployeeQuery when eager-loading is set.
	Edges                          InvitationEmployeeEdges `json:"edges"`
	branch_invitation_employees    *int
	invitation_invitation_employee *int
	tenant_invitation_employees    *int
	selectValues                   sql.SelectValues
}

// InvitationEmployeeEdges holds the relations/edges for other nodes in the graph.
type InvitationEmployeeEdges struct {
	// Invitation holds the value of the invitation edge.
	Invitation *Invitation `json:"invitation,omitempty"`
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// Branch holds the value of the branch edge.
	Branch *Branch `json:"branch,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// InvitationOrErr returns the Invitation value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvitationEmployeeEdges) InvitationOrErr() (*Invitation, error) {
	if e.Invitation != nil {
		return e.Invitation, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: invitation.Label}
	}
	return nil, &NotLoadedError{edge: "invitation"}
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvitationEmployeeEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// BranchOrErr returns the Branch value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InvitationEmployeeEdges) BranchOrErr() (*Branch, error) {
	if e.Branch != nil {
		return e.Branch, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: branch.Label}
	}
	return nil, &NotLoadedError{edge: "branch"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InvitationEmployee) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invitationemployee.FieldID:
			values[i] = new(sql.NullInt64)
		case invitationemployee.FieldDepartment, invitationemployee.FieldPosition:
			values[i] = new(sql.NullString)
		case invitationemployee.ForeignKeys[0]: // branch_invitation_employees
			values[i] = new(sql.NullInt64)
		case invitationemployee.ForeignKeys[1]: // invitation_invitation_employee
			values[i] = new(sql.NullInt64)
		case invitationemployee.ForeignKeys[2]: // tenant_invitation_employees
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InvitationEmployee fields.
func (_m *InvitationEmployee) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case invitationemployee.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case invitationemployee.FieldDepartment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field department", values[i])
			} else if value.Valid {
				_m.Department = value.String
			}
		case invitationemployee.FieldPosition:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				_m.Position = value.String
			}
		case invitationemployee.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field branch_invitation_employees", value)
			} else if value.Valid {
				_m.branch_invitation_employees = new(int)
				*_m.branch_invitation_employees = int(value.Int64)
			}
		case invitationemployee.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field invitation_invitation_employee", value)
			} else if value.Valid {
				_m.invitation_invitation_employee = new(int)
				*_m.invitation_invitation_employee = int(value.Int64)
			}
		case invitationemployee.ForeignKeys[2]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field tenant_invitation_employees", value)
			} else if value.Valid {
				_m.tenant_invitation_employees = new(int)
				*_m.tenant_invitation_employees = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InvitationEmployee.
// This includes values selected through modifiers, order, etc.
func (_m *InvitationEmployee) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryInvitation queries the "invitation" edge of the InvitationEmployee entity.
func (_m *InvitationEmployee) QueryInvitation() *InvitationQuery {
	return NewInvitationEmployeeClient(_m.config).QueryInvitation(_m)
}

// QueryTenant queries the "tenant" edge of the InvitationEmployee entity.
func (_m *InvitationEmployee) QueryTenant() *TenantQuery {
	return NewInvitationEmployeeClient(_m.config).QueryTenant(_m)
}

// QueryBranch queries the "branch" edge of the InvitationEmployee entity.
func (_m *InvitationEmployee) QueryBranch() *BranchQuery {
	return NewInvitationEmployeeClient(_m.config).QueryBranch(_m)
}

// Update returns a builder for updating this InvitationEmployee.
// Note that you need to call InvitationEmployee.Unwrap() before calling this method if this InvitationEmployee
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InvitationEmployee) Update() *InvitationEmployeeUpdateOne {
	return NewInvitationEmployeeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InvitationEmployee entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InvitationEmployee) Unwrap() *InvitationEmployee {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InvitationEmployee is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InvitationEmployee) String() string {
	var builder strings.Builder
	builder.WriteString("InvitationEmployee(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("department=")
	builder.WriteString(_m.Department)
	builder.WriteString(", ")
	builder.WriteString("position=")
	builder.WriteString(_m.Position)
	builder.WriteByte(')')
	return builder.String()
}

// InvitationEmployees is a parsable slice of InvitationEmployee.
type InvitationEmployees []*InvitationEmployee
