// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"saas_identidad/ent/branch"
	"saas_identidad/ent/invitation"
	"saas_identidad/ent/invitationemployee"
	"saas_identidad/ent/tenant"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InvitationEmployeeCreate is the builder for creating a InvitationEmployee entity.
type InvitationEmployeeCreate struct {
	config
	mutation *InvitationEmployeeMutation
	hooks    []Hook
}

// SetDepartment sets the "department" field.
func (_c *InvitationEmployeeCreate) SetDepartment(v string) *InvitationEmployeeCreate {
	_c.mutation.SetDepartment(v)
	return _c
}

// SetPosition sets the "position" field.
func (_c *InvitationEmployeeCreate) SetPosition(v string) *InvitationEmployeeCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetInvitationID sets the "invitation" edge to the Invitation entity by ID.
func (_c *InvitationEmployeeCreate) SetInvitationID(id int) *InvitationEmployeeCreate {
	_c.mutation.SetInvitationID(id)
	return _c
}

// SetNillableInvitationID sets the "invitation" edge to the Invitation entity by ID if the given value is not nil.
func (_c *InvitationEmployeeCreate) SetNillableInvitationID(id *int) *InvitationEmployeeCreate {
	if id != nil {
		_c = _c.SetInvitationID(*id)
	}
	return _c
}

// SetInvitation sets the "invitation" edge to the Invitation entity.
func (_c *InvitationEmployeeCreate) SetInvitation(v *Invitation) *InvitationEmployeeCreate {
	return _c.SetInvitationID(v.ID)
}

// SetTenantID sets the "tenant" edge to the Tenant entity by ID.
func (_c *InvitationEmployeeCreate) SetTenantID(id int) *InvitationEmployeeCreate {
	_c.mutation.SetTenantID(id)
	return _c
}

// SetNillableTenantID sets the "tenant" edge to the Tenant entity by ID if the given value is not nil.
func (_c *InvitationEmployeeCreate) SetNillableTenantID(id *int) *InvitationEmployeeCreate {
	if id != nil {
		_c = _c.SetTenantID(*id)
	}
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *InvitationEmployeeCreate) SetTenant(v *Tenant) *InvitationEmployeeCreate {
	return _c.SetTenantID(v.ID)
}

// SetBranchID sets the "branch" edge to the Branch entity by ID.
func (_c *InvitationEmployeeCreate) SetBranchID(id int) *InvitationEmployeeCreate {
	_c.mutation.SetBranchID(id)
	return _c
}

// SetNillableBranchID sets the "branch" edge to the Branch entity by ID if the given value is not nil.
func (_c *InvitationEmployeeCreate) SetNillableBranchID(id *int) *InvitationEmployeeCreate {
	if id != nil {
		_c = _c.SetBranchID(*id)
	}
	return _c
}

// SetBranch sets the "branch" edge to the Branch entity.
func (_c *InvitationEmployeeCreate) SetBranch(v *Branch) *InvitationEmployeeCreate {
	return _c.SetBranchID(v.ID)
}

// Mutation returns the InvitationEmployeeMutation object of the builder.
func (_c *InvitationEmployeeCreate) Mutation() *InvitationEmployeeMutation {
	return _c.mutation
}

// Save creates the InvitationEmployee in the database.
func (_c *InvitationEmployeeCreate) Save(ctx context.Context) (*InvitationEmployee, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvitationEmployeeCreate) SaveX(ctx context.Context) *InvitationEmployee {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvitationEmployeeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvitationEmployeeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvitationEmployeeCreate) check() error {
	if _, ok := _c.mutation.Department(); !ok {
		return &ValidationError{Name: "department", err: errors.New(`ent: missing required field "InvitationEmployee.department"`)}
	}
	if v, ok := _c.mutation.Department(); ok {
		if err := invitationemployee.DepartmentValidator(v); err != nil {
			return &ValidationError{Name: "department", err: fmt.Errorf(`ent: validator failed for field "InvitationEmployee.department": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "InvitationEmployee.position"`)}
	}
	if v, ok := _c.mutation.Position(); ok {
		if err := invitationemployee.PositionValidator(v); err != nil {
			return &ValidationError{Name: "position", err: fmt.Errorf(`ent: validator failed for field "InvitationEmployee.position": %w`, err)}
		}
	}
	return nil
}

func (_c *InvitationEmployeeCreate) sqlSave(ctx context.Context) (*InvitationEmployee, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvitationEmployeeCreate) createSpec() (*InvitationEmployee, *sqlgraph.CreateSpec) {
	var (
		_node = &InvitationEmployee{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invitationemployee.Table, sqlgraph.NewFieldSpec(invitationemployee.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Department(); ok {
		_spec.SetField(invitationemployee.FieldDepartment, field.TypeString, value)
		_node.Department = value
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(invitationemployee.FieldPosition, field.TypeString, value)
		_node.Position = value
	}
	if nodes := _c.mutation.InvitationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   invitationemployee.InvitationTable,
			Columns: []string{invitationemployee.InvitationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.invitation_invitation_employee = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitationemployee.TenantTable,
			Columns: []string{invitationemployee.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.tenant_invitation_employees = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BranchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitationemployee.BranchTable,
			Columns: []string{invitationemployee.BranchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(branch.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.branch_invitation_employees = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// InvitationEmployeeCreateBulk is the builder for creating many InvitationEmployee entities in bulk.
type InvitationEmployeeCreateBulk struct {
	config
	err      error
	builders []*InvitationEmployeeCreate
}

// Save creates the InvitationEmployee entities in the database.
func (_c *InvitationEmployeeCreateBulk) Save(ctx context.Context) ([]*InvitationEmployee, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InvitationEmployee, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvitationEmployeeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvitationEmployeeCreateBulk) SaveX(ctx context.Context) []*InvitationEmployee {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvitationEmployeeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvitationEmployeeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
