// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"saas_identidad/ent/plan"
	"saas_identidad/ent/tenant"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PlanCreate is the builder for creating a Plan entity.
type PlanCreate struct {
	config
	mutation *PlanMutation
	hooks    []Hook
}

// SetSubscription sets the "subscription" field.
func (_c *PlanCreate) SetSubscription(v string) *PlanCreate {
	_c.mutation.SetSubscription(v)
	return _c
}

// SetPrice sets the "price" field.
func (_c *PlanCreate) SetPrice(v float64) *PlanCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_c *PlanCreate) SetNillablePrice(v *float64) *PlanCreate {
	if v != nil {
		_c.SetPrice(*v)
	}
	return _c
}

// SetMaxEmployees sets the "max_employees" field.
func (_c *PlanCreate) SetMaxEmployees(v int32) *PlanCreate {
	_c.mutation.SetMaxEmployees(v)
	return _c
}

// SetNillableMaxEmployees sets the "max_employees" field if the given value is not nil.
func (_c *PlanCreate) SetNillableMaxEmployees(v *int32) *PlanCreate {
	if v != nil {
		_c.SetMaxEmployees(*v)
	}
	return _c
}

// SetMaxBranches sets the "max_branches" field.
func (_c *PlanCreate) SetMaxBranches(v int32) *PlanCreate {
	_c.mutation.SetMaxBranches(v)
	return _c
}

// SetNillableMaxBranches sets the "max_branches" field if the given value is not nil.
func (_c *PlanCreate) SetNillableMaxBranches(v *int32) *PlanCreate {
	if v != nil {
		_c.SetMaxBranches(*v)
	}
	return _c
}

// SetMaxBosses sets the "max_bosses" field.
func (_c *PlanCreate) SetMaxBosses(v int32) *PlanCreate {
	_c.mutation.SetMaxBosses(v)
	return _c
}

// SetNillableMaxBosses sets the "max_bosses" field if the given value is not nil.
func (_c *PlanCreate) SetNillableMaxBosses(v *int32) *PlanCreate {
	if v != nil {
		_c.SetMaxBosses(*v)
	}
	return _c
}

// AddTenantIDs adds the "tenants" edge to the Tenant entity by IDs.
func (_c *PlanCreate) AddTenantIDs(ids ...int) *PlanCreate {
	_c.mutation.AddTenantIDs(ids...)
	return _c
}

// AddTenants adds the "tenants" edges to the Tenant entity.
func (_c *PlanCreate) AddTenants(v ...*Tenant) *PlanCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTenantIDs(ids...)
}

// Mutation returns the PlanMutation object of the builder.
func (_c *PlanCreate) Mutation() *PlanMutation {
	return _c.mutation
}

// Save creates the Plan in the database.
func (_c *PlanCreate) Save(ctx context.Context) (*Plan, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlanCreate) SaveX(ctx context.Context) *Plan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlanCreate) defaults() {
	if _, ok := _c.mutation.Price(); !ok {
		v := plan.DefaultPrice
		_c.mutation.SetPrice(v)
	}
	if _, ok := _c.mutation.MaxEmployees(); !ok {
		v := plan.DefaultMaxEmployees
		_c.mutation.SetMaxEmployees(v)
	}
	if _, ok := _c.mutation.MaxBranches(); !ok {
		v := plan.DefaultMaxBranches
		_c.mutation.SetMaxBranches(v)
	}
	if _, ok := _c.mutation.MaxBosses(); !ok {
		v := plan.DefaultMaxBosses
		_c.mutation.SetMaxBosses(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlanCreate) check() error {
	if _, ok := _c.mutation.Subscription(); !ok {
		return &ValidationError{Name: "subscription", err: errors.New(`ent: missing required field "Plan.subscription"`)}
	}
	if v, ok := _c.mutation.Subscription(); ok {
		if err := plan.SubscriptionValidator(v); err != nil {
			return &ValidationError{Name: "subscription", err: fmt.Errorf(`ent: validator failed for field "Plan.subscription": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "Plan.price"`)}
	}
	if _, ok := _c.mutation.MaxEmployees(); !ok {
		return &ValidationError{Name: "max_employees", err: errors.New(`ent: missing required field "Plan.max_employees"`)}
	}
	if _, ok := _c.mutation.MaxBranches(); !ok {
		return &ValidationError{Name: "max_branches", err: errors.New(`ent: missing required field "Plan.max_branches"`)}
	}
	if _, ok := _c.mutation.MaxBosses(); !ok {
		return &ValidationError{Name: "max_bosses", err: errors.New(`ent: missing required field "Plan.max_bosses"`)}
	}
	return nil
}

func (_c *PlanCreate) sqlSave(ctx context.Context) (*Plan, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlanCreate) createSpec() (*Plan, *sqlgraph.CreateSpec) {
	var (
		_node = &Plan{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(plan.Table, sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Subscription(); ok {
		_spec.SetField(plan.FieldSubscription, field.TypeString, value)
		_node.Subscription = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(plan.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.MaxEmployees(); ok {
		_spec.SetField(plan.FieldMaxEmployees, field.TypeInt32, value)
		_node.MaxEmployees = value
	}
	if value, ok := _c.mutation.MaxBranches(); ok {
		_spec.SetField(plan.FieldMaxBranches, field.TypeInt32, value)
		_node.MaxBranches = value
	}
	if value, ok := _c.mutation.MaxBosses(); ok {
		_spec.SetField(plan.FieldMaxBosses, field.TypeInt32, value)
		_node.MaxBosses = value
	}
	if nodes := _c.mutation.TenantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.TenantsTable,
			Columns: []string{plan.TenantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PlanCreateBulk is the builder for creating many Plan entities in bulk.
type PlanCreateBulk struct {
	config
	err      error
	builders []*PlanCreate
}

// Save creates the Plan entities in the database.
func (_c *PlanCreateBulk) Save(ctx context.Context) ([]*Plan, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Plan, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlanCreateBulk) SaveX(ctx context.Context) []*Plan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
