// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"saas_identidad/ent/branch"
	"saas_identidad/ent/employee"
	"saas_identidad/ent/plan"
	"saas_identidad/ent/predicate"
	"saas_identidad/ent/tenant"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TenantUpdate is the builder for updating Tenant entities.
type TenantUpdate struct {
	config
	hooks    []Hook
	mutation *TenantMutation
}

// Where appends a list predicates to the TenantUpdate builder.
func (_u *TenantUpdate) Where(ps ...predicate.Tenant) *TenantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TenantUpdate) SetName(v string) *TenantUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableName(v *string) *TenantUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEndSuscription sets the "end_suscription" field.
func (_u *TenantUpdate) SetEndSuscription(v time.Time) *TenantUpdate {
	_u.mutation.SetEndSuscription(v)
	return _u
}

// SetNillableEndSuscription sets the "end_suscription" field if the given value is not nil.
func (_u *TenantUpdate) SetNillableEndSuscription(v *time.Time) *TenantUpdate {
	if v != nil {
		_u.SetEndSuscription(*v)
	}
	return _u
}

// ClearEndSuscription clears the value of the "end_suscription" field.
func (_u *TenantUpdate) ClearEndSuscription() *TenantUpdate {
	_u.mutation.ClearEndSuscription()
	return _u
}

// SetPlanID sets the "plan" edge to the Plan entity by ID.
func (_u *TenantUpdate) SetPlanID(id int) *TenantUpdate {
	_u.mutation.SetPlanID(id)
	return _u
}

// SetNillablePlanID sets the "plan" edge to the Plan entity by ID if the given value is not nil.
func (_u *TenantUpdate) SetNillablePlanID(id *int) *TenantUpdate {
	if id != nil {
		_u = _u.SetPlanID(*id)
	}
	return _u
}

// SetPlan sets the "plan" edge to the Plan entity.
func (_u *TenantUpdate) SetPlan(v *Plan) *TenantUpdate {
	return _u.SetPlanID(v.ID)
}

// AddEmployeeIDs adds the "employees" edge to the Employee entity by IDs.
func (_u *TenantUpdate) AddEmployeeIDs(ids ...int) *TenantUpdate {
	_u.mutation.AddEmployeeIDs(ids...)
	return _u
}

// AddEmployees adds the "employees" edges to the Employee entity.
func (_u *TenantUpdate) AddEmployees(v ...*Employee) *TenantUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEmployeeIDs(ids...)
}

// AddBranchIDs adds the "branchs" edge to the Branch entity by IDs.
func (_u *TenantUpdate) AddBranchIDs(ids ...int) *TenantUpdate {
	_u.mutation.AddBranchIDs(ids...)
	return _u
}

// AddBranchs adds the "branchs" edges to the Branch entity.
func (_u *TenantUpdate) AddBranchs(v ...*Branch) *TenantUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBranchIDs(ids...)
}

// Mutation returns the TenantMutation object of the builder.
func (_u *TenantUpdate) Mutation() *TenantMutation {
	return _u.mutation
}

// ClearPlan clears the "plan" edge to the Plan entity.
func (_u *TenantUpdate) ClearPlan() *TenantUpdate {
	_u.mutation.ClearPlan()
	return _u
}

// ClearEmployees clears all "employees" edges to the Employee entity.
func (_u *TenantUpdate) ClearEmployees() *TenantUpdate {
	_u.mutation.ClearEmployees()
	return _u
}

// RemoveEmployeeIDs removes the "employees" edge to Employee entities by IDs.
func (_u *TenantUpdate) RemoveEmployeeIDs(ids ...int) *TenantUpdate {
	_u.mutation.RemoveEmployeeIDs(ids...)
	return _u
}

// RemoveEmployees removes "employees" edges to Employee entities.
func (_u *TenantUpdate) RemoveEmployees(v ...*Employee) *TenantUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEmployeeIDs(ids...)
}

// ClearBranchs clears all "branchs" edges to the Branch entity.
func (_u *TenantUpdate) ClearBranchs() *TenantUpdate {
	_u.mutation.ClearBranchs()
	return _u
}

// RemoveBranchIDs removes the "branchs" edge to Branch entities by IDs.
func (_u *TenantUpdate) RemoveBranchIDs(ids ...int) *TenantUpdate {
	_u.mutation.RemoveBranchIDs(ids...)
	return _u
}

// RemoveBranchs removes "branchs" edges to Branch entities.
func (_u *TenantUpdate) RemoveBranchs(v ...*Branch) *TenantUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBranchIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tenant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tenant.name": %w`, err)}
		}
	}
	return nil
}

func (_u *TenantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.EndSuscription(); ok {
		_spec.SetField(tenant.FieldEndSuscription, field.TypeTime, value)
	}
	if _u.mutation.EndSuscriptionCleared() {
		_spec.ClearField(tenant.FieldEndSuscription, field.TypeTime)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenant.PlanTable,
			Columns: []string{tenant.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenant.PlanTable,
			Columns: []string{tenant.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EmployeesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.EmployeesTable,
			Columns: []string{tenant.EmployeesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEmployeesIDs(); len(nodes) > 0 && !_u.mutation.EmployeesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.EmployeesTable,
			Columns: []string{tenant.EmployeesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmployeesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.EmployeesTable,
			Columns: []string{tenant.EmployeesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BranchsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.BranchsTable,
			Columns: []string{tenant.BranchsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(branch.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBranchsIDs(); len(nodes) > 0 && !_u.mutation.BranchsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.BranchsTable,
			Columns: []string{tenant.BranchsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(branch.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BranchsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.BranchsTable,
			Columns: []string{tenant.BranchsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(branch.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantUpdateOne is the builder for updating a single Tenant entity.
type TenantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantMutation
}

// SetName sets the "name" field.
func (_u *TenantUpdateOne) SetName(v string) *TenantUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableName(v *string) *TenantUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEndSuscription sets the "end_suscription" field.
func (_u *TenantUpdateOne) SetEndSuscription(v time.Time) *TenantUpdateOne {
	_u.mutation.SetEndSuscription(v)
	return _u
}

// SetNillableEndSuscription sets the "end_suscription" field if the given value is not nil.
func (_u *TenantUpdateOne) SetNillableEndSuscription(v *time.Time) *TenantUpdateOne {
	if v != nil {
		_u.SetEndSuscription(*v)
	}
	return _u
}

// ClearEndSuscription clears the value of the "end_suscription" field.
func (_u *TenantUpdateOne) ClearEndSuscription() *TenantUpdateOne {
	_u.mutation.ClearEndSuscription()
	return _u
}

// SetPlanID sets the "plan" edge to the Plan entity by ID.
func (_u *TenantUpdateOne) SetPlanID(id int) *TenantUpdateOne {
	_u.mutation.SetPlanID(id)
	return _u
}

// SetNillablePlanID sets the "plan" edge to the Plan entity by ID if the given value is not nil.
func (_u *TenantUpdateOne) SetNillablePlanID(id *int) *TenantUpdateOne {
	if id != nil {
		_u = _u.SetPlanID(*id)
	}
	return _u
}

// SetPlan sets the "plan" edge to the Plan entity.
func (_u *TenantUpdateOne) SetPlan(v *Plan) *TenantUpdateOne {
	return _u.SetPlanID(v.ID)
}

// AddEmployeeIDs adds the "employees" edge to the Employee entity by IDs.
func (_u *TenantUpdateOne) AddEmployeeIDs(ids ...int) *TenantUpdateOne {
	_u.mutation.AddEmployeeIDs(ids...)
	return _u
}

// AddEmployees adds the "employees" edges to the Employee entity.
func (_u *TenantUpdateOne) AddEmployees(v ...*Employee) *TenantUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEmployeeIDs(ids...)
}

// AddBranchIDs adds the "branchs" edge to the Branch entity by IDs.
func (_u *TenantUpdateOne) AddBranchIDs(ids ...int) *TenantUpdateOne {
	_u.mutation.AddBranchIDs(ids...)
	return _u
}

// AddBranchs adds the "branchs" edges to the Branch entity.
func (_u *TenantUpdateOne) AddBranchs(v ...*Branch) *TenantUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBranchIDs(ids...)
}

// Mutation returns the TenantMutation object of the builder.
func (_u *TenantUpdateOne) Mutation() *TenantMutation {
	return _u.mutation
}

// ClearPlan clears the "plan" edge to the Plan entity.
func (_u *TenantUpdateOne) ClearPlan() *TenantUpdateOne {
	_u.mutation.ClearPlan()
	return _u
}

// ClearEmployees clears all "employees" edges to the Employee entity.
func (_u *TenantUpdateOne) ClearEmployees() *TenantUpdateOne {
	_u.mutation.ClearEmployees()
	return _u
}

// RemoveEmployeeIDs removes the "employees" edge to Employee entities by IDs.
func (_u *TenantUpdateOne) RemoveEmployeeIDs(ids ...int) *TenantUpdateOne {
	_u.mutation.RemoveEmployeeIDs(ids...)
	return _u
}

// RemoveEmployees removes "employees" edges to Employee entities.
func (_u *TenantUpdateOne) RemoveEmployees(v ...*Employee) *TenantUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEmployeeIDs(ids...)
}

// ClearBranchs clears all "branchs" edges to the Branch entity.
func (_u *TenantUpdateOne) ClearBranchs() *TenantUpdateOne {
	_u.mutation.ClearBranchs()
	return _u
}

// RemoveBranchIDs removes the "branchs" edge to Branch entities by IDs.
func (_u *TenantUpdateOne) RemoveBranchIDs(ids ...int) *TenantUpdateOne {
	_u.mutation.RemoveBranchIDs(ids...)
	return _u
}

// RemoveBranchs removes "branchs" edges to Branch entities.
func (_u *TenantUpdateOne) RemoveBranchs(v ...*Branch) *TenantUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBranchIDs(ids...)
}

// Where appends a list predicates to the TenantUpdate builder.
func (_u *TenantUpdateOne) Where(ps ...predicate.Tenant) *TenantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantUpdateOne) Select(field string, fields ...string) *TenantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Tenant entity.
func (_u *TenantUpdateOne) Save(ctx context.Context) (*Tenant, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantUpdateOne) SaveX(ctx context.Context) *Tenant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tenant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tenant.name": %w`, err)}
		}
	}
	return nil
}

func (_u *TenantUpdateOne) sqlSave(ctx context.Context) (_node *Tenant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tenant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenant.FieldID)
		for _, f := range fields {
			if !tenant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.EndSuscription(); ok {
		_spec.SetField(tenant.FieldEndSuscription, field.TypeTime, value)
	}
	if _u.mutation.EndSuscriptionCleared() {
		_spec.ClearField(tenant.FieldEndSuscription, field.TypeTime)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenant.PlanTable,
			Columns: []string{tenant.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenant.PlanTable,
			Columns: []string{tenant.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EmployeesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.EmployeesTable,
			Columns: []string{tenant.EmployeesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEmployeesIDs(); len(nodes) > 0 && !_u.mutation.EmployeesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.EmployeesTable,
			Columns: []string{tenant.EmployeesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmployeesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.EmployeesTable,
			Columns: []string{tenant.EmployeesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BranchsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.BranchsTable,
			Columns: []string{tenant.BranchsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(branch.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBranchsIDs(); len(nodes) > 0 && !_u.mutation.BranchsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.BranchsTable,
			Columns: []string{tenant.BranchsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(branch.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BranchsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.BranchsTable,
			Columns: []string{tenant.BranchsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(branch.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Tenant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
