// Code generated by ent, DO NOT EDIT.

package employee

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the employee type in the database.
	Label = "employee"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDepartment holds the string denoting the department field in the database.
	FieldDepartment = "department"
	// FieldPosition holds the string denoting the position field in the database.
	FieldPosition = "position"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// FieldJoinAt holds the string denoting the join_at field in the database.
	FieldJoinAt = "join_at"
	// FieldLeftAt holds the string denoting the left_at field in the database.
	FieldLeftAt = "left_at"
	// EdgeEmails holds the string denoting the emails edge name in mutations.
	EdgeEmails = "emails"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// EdgeBranches holds the string denoting the branches edge name in mutations.
	EdgeBranches = "branches"
	// Table holds the table name of the employee in the database.
	Table = "employees"
	// EmailsTable is the table that holds the emails relation/edge.
	EmailsTable = "employees"
	// EmailsInverseTable is the table name for the Email entity.
	// It exists in this package in order to avoid circular dependency with the "email" package.
	EmailsInverseTable = "emails"
	// EmailsColumn is the table column denoting the emails relation/edge.
	EmailsColumn = "email_employees"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "employees"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenants"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_employees"
	// BranchesTable is the table that holds the branches relation/edge.
	BranchesTable = "employees"
	// BranchesInverseTable is the table name for the Branch entity.
	// It exists in this package in order to avoid circular dependency with the "branch" package.
	BranchesInverseTable = "branches"
	// BranchesColumn is the table column denoting the branches relation/edge.
	BranchesColumn = "branch_employees"
)

// Columns holds all SQL columns for employee fields.
var Columns = []string{
	FieldID,
	FieldDepartment,
	FieldPosition,
	FieldActive,
	FieldJoinAt,
	FieldLeftAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "employees"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"branch_employees",
	"email_employees",
	"tenant_employees",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "saas_identidad/ent/runtime"
var (
	Hooks [1]ent.Hook
	// PositionValidator is a validator for the "position" field. It is called by the builders before save.
	PositionValidator func(string) error
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive bool
	// DefaultJoinAt holds the default value on creation for the "join_at" field.
	DefaultJoinAt func() time.Time
)

// Department defines the type for the "department" enum field.
type Department string

// Department values.
const (
	DepartmentOffice     Department = "office"
	DepartmentLogistics  Department = "logistics"
	DepartmentPlant      Department = "plant"
	DepartmentCommercial Department = "commercial"
)

func (d Department) String() string {
	return string(d)
}

// DepartmentValidator is a validator for the "department" field enum values. It is called by the builders before save.
func DepartmentValidator(d Department) error {
	switch d {
	case DepartmentOffice, DepartmentLogistics, DepartmentPlant, DepartmentCommercial:
		return nil
	default:
		return fmt.Errorf("employee: invalid enum value for department field: %q", d)
	}
}

// OrderOption defines the ordering options for the Employee queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDepartment orders the results by the department field.
func ByDepartment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDepartment, opts...).ToFunc()
}

// ByPosition orders the results by the position field.
func ByPosition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPosition, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}

// ByJoinAt orders the results by the join_at field.
func ByJoinAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJoinAt, opts...).ToFunc()
}

// ByLeftAt orders the results by the left_at field.
func ByLeftAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLeftAt, opts...).ToFunc()
}

// ByEmailsField orders the results by emails field.
func ByEmailsField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEmailsStep(), sql.OrderByField(field, opts...))
	}
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}

// ByBranchesField orders the results by branches field.
func ByBranchesField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBranchesStep(), sql.OrderByField(field, opts...))
	}
}
func newEmailsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EmailsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EmailsTable, EmailsColumn),
	)
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
	)
}
func newBranchesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BranchesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, BranchesTable, BranchesColumn),
	)
}
