// Code generated by ent, DO NOT EDIT.

package invitation

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the invitation type in the database.
	Label = "invitation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// FieldAccount holds the string denoting the account field in the database.
	FieldAccount = "account"
	// FieldExpireAt holds the string denoting the expire_at field in the database.
	FieldExpireAt = "expire_at"
	// Table holds the table name of the invitation in the database.
	Table = "invitations"
)

// Columns holds all SQL columns for invitation fields.
var Columns = []string{
	FieldID,
	FieldEmail,
	FieldToken,
	FieldAccount,
	FieldExpireAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// TokenValidator is a validator for the "token" field. It is called by the builders before save.
	TokenValidator func(string) error
	// DefaultExpireAt holds the default value on creation for the "expire_at" field.
	DefaultExpireAt time.Time
)

// Account defines the type for the "account" enum field.
type Account string

// Account values.
const (
	AccountDEVELOPER Account = "DEVELOPER"
	AccountUSER      Account = "USER"
	AccountADMIN     Account = "ADMIN"
)

func (a Account) String() string {
	return string(a)
}

// AccountValidator is a validator for the "account" field enum values. It is called by the builders before save.
func AccountValidator(a Account) error {
	switch a {
	case AccountDEVELOPER, AccountUSER, AccountADMIN:
		return nil
	default:
		return fmt.Errorf("invitation: invalid enum value for account field: %q", a)
	}
}

// OrderOption defines the ordering options for the Invitation queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByToken orders the results by the token field.
func ByToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToken, opts...).ToFunc()
}

// ByAccount orders the results by the account field.
func ByAccount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccount, opts...).ToFunc()
}

// ByExpireAt orders the results by the expire_at field.
func ByExpireAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpireAt, opts...).ToFunc()
}
