// Code generated by ent, DO NOT EDIT.

package plan

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the plan type in the database.
	Label = "plan"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSubscription holds the string denoting the subscription field in the database.
	FieldSubscription = "subscription"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldMaxEmployees holds the string denoting the max_employees field in the database.
	FieldMaxEmployees = "max_employees"
	// FieldMaxBranches holds the string denoting the max_branches field in the database.
	FieldMaxBranches = "max_branches"
	// FieldMaxBosses holds the string denoting the max_bosses field in the database.
	FieldMaxBosses = "max_bosses"
	// EdgeTenants holds the string denoting the tenants edge name in mutations.
	EdgeTenants = "tenants"
	// Table holds the table name of the plan in the database.
	Table = "plans"
	// TenantsTable is the table that holds the tenants relation/edge.
	TenantsTable = "tenants"
	// TenantsInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantsInverseTable = "tenants"
	// TenantsColumn is the table column denoting the tenants relation/edge.
	TenantsColumn = "plan_tenants"
)

// Columns holds all SQL columns for plan fields.
var Columns = []string{
	FieldID,
	FieldSubscription,
	FieldPrice,
	FieldMaxEmployees,
	FieldMaxBranches,
	FieldMaxBosses,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SubscriptionValidator is a validator for the "subscription" field. It is called by the builders before save.
	SubscriptionValidator func(string) error
	// DefaultPrice holds the default value on creation for the "price" field.
	DefaultPrice float64
	// DefaultMaxEmployees holds the default value on creation for the "max_employees" field.
	DefaultMaxEmployees int32
	// DefaultMaxBranches holds the default value on creation for the "max_branches" field.
	DefaultMaxBranches int32
	// DefaultMaxBosses holds the default value on creation for the "max_bosses" field.
	DefaultMaxBosses int32
)

// OrderOption defines the ordering options for the Plan queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySubscription orders the results by the subscription field.
func BySubscription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscription, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByMaxEmployees orders the results by the max_employees field.
func ByMaxEmployees(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxEmployees, opts...).ToFunc()
}

// ByMaxBranches orders the results by the max_branches field.
func ByMaxBranches(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxBranches, opts...).ToFunc()
}

// ByMaxBosses orders the results by the max_bosses field.
func ByMaxBosses(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxBosses, opts...).ToFunc()
}

// ByTenantsCount orders the results by tenants count.
func ByTenantsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTenantsStep(), opts...)
	}
}

// ByTenants orders the results by tenants terms.
func ByTenants(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTenantsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TenantsTable, TenantsColumn),
	)
}
