// Code generated by ent, DO NOT EDIT.

package plan

import (
	"saas_identidad/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldID, id))
}

// Subscription applies equality check predicate on the "subscription" field. It's identical to SubscriptionEQ.
func Subscription(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldSubscription, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldPrice, v))
}

// MaxEmployees applies equality check predicate on the "max_employees" field. It's identical to MaxEmployeesEQ.
func MaxEmployees(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldMaxEmployees, v))
}

// MaxBranches applies equality check predicate on the "max_branches" field. It's identical to MaxBranchesEQ.
func MaxBranches(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldMaxBranches, v))
}

// MaxBosses applies equality check predicate on the "max_bosses" field. It's identical to MaxBossesEQ.
func MaxBosses(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldMaxBosses, v))
}

// SubscriptionEQ applies the EQ predicate on the "subscription" field.
func SubscriptionEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldSubscription, v))
}

// SubscriptionNEQ applies the NEQ predicate on the "subscription" field.
func SubscriptionNEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldSubscription, v))
}

// SubscriptionIn applies the In predicate on the "subscription" field.
func SubscriptionIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldSubscription, vs...))
}

// SubscriptionNotIn applies the NotIn predicate on the "subscription" field.
func SubscriptionNotIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldSubscription, vs...))
}

// SubscriptionGT applies the GT predicate on the "subscription" field.
func SubscriptionGT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldSubscription, v))
}

// SubscriptionGTE applies the GTE predicate on the "subscription" field.
func SubscriptionGTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldSubscription, v))
}

// SubscriptionLT applies the LT predicate on the "subscription" field.
func SubscriptionLT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldSubscription, v))
}

// SubscriptionLTE applies the LTE predicate on the "subscription" field.
func SubscriptionLTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldSubscription, v))
}

// SubscriptionContains applies the Contains predicate on the "subscription" field.
func SubscriptionContains(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContains(FieldSubscription, v))
}

// SubscriptionHasPrefix applies the HasPrefix predicate on the "subscription" field.
func SubscriptionHasPrefix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasPrefix(FieldSubscription, v))
}

// SubscriptionHasSuffix applies the HasSuffix predicate on the "subscription" field.
func SubscriptionHasSuffix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasSuffix(FieldSubscription, v))
}

// SubscriptionEqualFold applies the EqualFold predicate on the "subscription" field.
func SubscriptionEqualFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEqualFold(FieldSubscription, v))
}

// SubscriptionContainsFold applies the ContainsFold predicate on the "subscription" field.
func SubscriptionContainsFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContainsFold(FieldSubscription, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldPrice, v))
}

// MaxEmployeesEQ applies the EQ predicate on the "max_employees" field.
func MaxEmployeesEQ(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldMaxEmployees, v))
}

// MaxEmployeesNEQ applies the NEQ predicate on the "max_employees" field.
func MaxEmployeesNEQ(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldMaxEmployees, v))
}

// MaxEmployeesIn applies the In predicate on the "max_employees" field.
func MaxEmployeesIn(vs ...int32) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldMaxEmployees, vs...))
}

// MaxEmployeesNotIn applies the NotIn predicate on the "max_employees" field.
func MaxEmployeesNotIn(vs ...int32) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldMaxEmployees, vs...))
}

// MaxEmployeesGT applies the GT predicate on the "max_employees" field.
func MaxEmployeesGT(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldMaxEmployees, v))
}

// MaxEmployeesGTE applies the GTE predicate on the "max_employees" field.
func MaxEmployeesGTE(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldMaxEmployees, v))
}

// MaxEmployeesLT applies the LT predicate on the "max_employees" field.
func MaxEmployeesLT(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldMaxEmployees, v))
}

// MaxEmployeesLTE applies the LTE predicate on the "max_employees" field.
func MaxEmployeesLTE(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldMaxEmployees, v))
}

// MaxBranchesEQ applies the EQ predicate on the "max_branches" field.
func MaxBranchesEQ(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldMaxBranches, v))
}

// MaxBranchesNEQ applies the NEQ predicate on the "max_branches" field.
func MaxBranchesNEQ(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldMaxBranches, v))
}

// MaxBranchesIn applies the In predicate on the "max_branches" field.
func MaxBranchesIn(vs ...int32) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldMaxBranches, vs...))
}

// MaxBranchesNotIn applies the NotIn predicate on the "max_branches" field.
func MaxBranchesNotIn(vs ...int32) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldMaxBranches, vs...))
}

// MaxBranchesGT applies the GT predicate on the "max_branches" field.
func MaxBranchesGT(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldMaxBranches, v))
}

// MaxBranchesGTE applies the GTE predicate on the "max_branches" field.
func MaxBranchesGTE(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldMaxBranches, v))
}

// MaxBranchesLT applies the LT predicate on the "max_branches" field.
func MaxBranchesLT(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldMaxBranches, v))
}

// MaxBranchesLTE applies the LTE predicate on the "max_branches" field.
func MaxBranchesLTE(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldMaxBranches, v))
}

// MaxBossesEQ applies the EQ predicate on the "max_bosses" field.
func MaxBossesEQ(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldMaxBosses, v))
}

// MaxBossesNEQ applies the NEQ predicate on the "max_bosses" field.
func MaxBossesNEQ(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldMaxBosses, v))
}

// MaxBossesIn applies the In predicate on the "max_bosses" field.
func MaxBossesIn(vs ...int32) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldMaxBosses, vs...))
}

// MaxBossesNotIn applies the NotIn predicate on the "max_bosses" field.
func MaxBossesNotIn(vs ...int32) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldMaxBosses, vs...))
}

// MaxBossesGT applies the GT predicate on the "max_bosses" field.
func MaxBossesGT(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldMaxBosses, v))
}

// MaxBossesGTE applies the GTE predicate on the "max_bosses" field.
func MaxBossesGTE(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldMaxBosses, v))
}

// MaxBossesLT applies the LT predicate on the "max_bosses" field.
func MaxBossesLT(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldMaxBosses, v))
}

// MaxBossesLTE applies the LTE predicate on the "max_bosses" field.
func MaxBossesLTE(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldMaxBosses, v))
}

// HasTenants applies the HasEdge predicate on the "tenants" edge.
func HasTenants() predicate.Plan {
	return predicate.Plan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TenantsTable, TenantsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantsWith applies the HasEdge predicate on the "tenants" edge with a given conditions (other predicates).
func HasTenantsWith(preds ...predicate.Tenant) predicate.Plan {
	return predicate.Plan(func(s *sql.Selector) {
		step := newTenantsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Plan) predicate.Plan {
	return predicate.Plan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Plan) predicate.Plan {
	return predicate.Plan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Plan) predicate.Plan {
	return predicate.Plan(sql.NotPredicates(p))
}
