// Code generated by ent, DO NOT EDIT.

package plan

import (
	"saas_identidad/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldID, id))
}

// Subscription applies equality check predicate on the "subscription" field. It's identical to SubscriptionEQ.
func Subscription(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldSubscription, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldPrice, v))
}

// MaxUsers applies equality check predicate on the "max_users" field. It's identical to MaxUsersEQ.
func MaxUsers(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldMaxUsers, v))
}

// MaxBranch applies equality check predicate on the "max_branch" field. It's identical to MaxBranchEQ.
func MaxBranch(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldMaxBranch, v))
}

// MaxBoss applies equality check predicate on the "max_boss" field. It's identical to MaxBossEQ.
func MaxBoss(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldMaxBoss, v))
}

// SubscriptionEQ applies the EQ predicate on the "subscription" field.
func SubscriptionEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldSubscription, v))
}

// SubscriptionNEQ applies the NEQ predicate on the "subscription" field.
func SubscriptionNEQ(v string) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldSubscription, v))
}

// SubscriptionIn applies the In predicate on the "subscription" field.
func SubscriptionIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldSubscription, vs...))
}

// SubscriptionNotIn applies the NotIn predicate on the "subscription" field.
func SubscriptionNotIn(vs ...string) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldSubscription, vs...))
}

// SubscriptionGT applies the GT predicate on the "subscription" field.
func SubscriptionGT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldSubscription, v))
}

// SubscriptionGTE applies the GTE predicate on the "subscription" field.
func SubscriptionGTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldSubscription, v))
}

// SubscriptionLT applies the LT predicate on the "subscription" field.
func SubscriptionLT(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldSubscription, v))
}

// SubscriptionLTE applies the LTE predicate on the "subscription" field.
func SubscriptionLTE(v string) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldSubscription, v))
}

// SubscriptionContains applies the Contains predicate on the "subscription" field.
func SubscriptionContains(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContains(FieldSubscription, v))
}

// SubscriptionHasPrefix applies the HasPrefix predicate on the "subscription" field.
func SubscriptionHasPrefix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasPrefix(FieldSubscription, v))
}

// SubscriptionHasSuffix applies the HasSuffix predicate on the "subscription" field.
func SubscriptionHasSuffix(v string) predicate.Plan {
	return predicate.Plan(sql.FieldHasSuffix(FieldSubscription, v))
}

// SubscriptionEqualFold applies the EqualFold predicate on the "subscription" field.
func SubscriptionEqualFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldEqualFold(FieldSubscription, v))
}

// SubscriptionContainsFold applies the ContainsFold predicate on the "subscription" field.
func SubscriptionContainsFold(v string) predicate.Plan {
	return predicate.Plan(sql.FieldContainsFold(FieldSubscription, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldPrice, v))
}

// MaxUsersEQ applies the EQ predicate on the "max_users" field.
func MaxUsersEQ(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldMaxUsers, v))
}

// MaxUsersNEQ applies the NEQ predicate on the "max_users" field.
func MaxUsersNEQ(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldMaxUsers, v))
}

// MaxUsersIn applies the In predicate on the "max_users" field.
func MaxUsersIn(vs ...int32) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldMaxUsers, vs...))
}

// MaxUsersNotIn applies the NotIn predicate on the "max_users" field.
func MaxUsersNotIn(vs ...int32) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldMaxUsers, vs...))
}

// MaxUsersGT applies the GT predicate on the "max_users" field.
func MaxUsersGT(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldMaxUsers, v))
}

// MaxUsersGTE applies the GTE predicate on the "max_users" field.
func MaxUsersGTE(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldMaxUsers, v))
}

// MaxUsersLT applies the LT predicate on the "max_users" field.
func MaxUsersLT(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldMaxUsers, v))
}

// MaxUsersLTE applies the LTE predicate on the "max_users" field.
func MaxUsersLTE(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldMaxUsers, v))
}

// MaxBranchEQ applies the EQ predicate on the "max_branch" field.
func MaxBranchEQ(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldMaxBranch, v))
}

// MaxBranchNEQ applies the NEQ predicate on the "max_branch" field.
func MaxBranchNEQ(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldMaxBranch, v))
}

// MaxBranchIn applies the In predicate on the "max_branch" field.
func MaxBranchIn(vs ...int32) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldMaxBranch, vs...))
}

// MaxBranchNotIn applies the NotIn predicate on the "max_branch" field.
func MaxBranchNotIn(vs ...int32) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldMaxBranch, vs...))
}

// MaxBranchGT applies the GT predicate on the "max_branch" field.
func MaxBranchGT(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldMaxBranch, v))
}

// MaxBranchGTE applies the GTE predicate on the "max_branch" field.
func MaxBranchGTE(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldMaxBranch, v))
}

// MaxBranchLT applies the LT predicate on the "max_branch" field.
func MaxBranchLT(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldMaxBranch, v))
}

// MaxBranchLTE applies the LTE predicate on the "max_branch" field.
func MaxBranchLTE(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldMaxBranch, v))
}

// MaxBossEQ applies the EQ predicate on the "max_boss" field.
func MaxBossEQ(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldEQ(FieldMaxBoss, v))
}

// MaxBossNEQ applies the NEQ predicate on the "max_boss" field.
func MaxBossNEQ(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldNEQ(FieldMaxBoss, v))
}

// MaxBossIn applies the In predicate on the "max_boss" field.
func MaxBossIn(vs ...int32) predicate.Plan {
	return predicate.Plan(sql.FieldIn(FieldMaxBoss, vs...))
}

// MaxBossNotIn applies the NotIn predicate on the "max_boss" field.
func MaxBossNotIn(vs ...int32) predicate.Plan {
	return predicate.Plan(sql.FieldNotIn(FieldMaxBoss, vs...))
}

// MaxBossGT applies the GT predicate on the "max_boss" field.
func MaxBossGT(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldGT(FieldMaxBoss, v))
}

// MaxBossGTE applies the GTE predicate on the "max_boss" field.
func MaxBossGTE(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldGTE(FieldMaxBoss, v))
}

// MaxBossLT applies the LT predicate on the "max_boss" field.
func MaxBossLT(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldLT(FieldMaxBoss, v))
}

// MaxBossLTE applies the LTE predicate on the "max_boss" field.
func MaxBossLTE(v int32) predicate.Plan {
	return predicate.Plan(sql.FieldLTE(FieldMaxBoss, v))
}

// HasTenants applies the HasEdge predicate on the "tenants" edge.
func HasTenants() predicate.Plan {
	return predicate.Plan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TenantsTable, TenantsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantsWith applies the HasEdge predicate on the "tenants" edge with a given conditions (other predicates).
func HasTenantsWith(preds ...predicate.Tenant) predicate.Plan {
	return predicate.Plan(func(s *sql.Selector) {
		step := newTenantsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Plan) predicate.Plan {
	return predicate.Plan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Plan) predicate.Plan {
	return predicate.Plan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Plan) predicate.Plan {
	return predicate.Plan(sql.NotPredicates(p))
}
